
subdir := plash

all:

include ../Makeconfig

routines = filesysobj region comms cap-protocol cap-call-return marshal-pack \
	   cap-utils serialise \
	   libc-comms libc-misc libc-stat libc-truncate libc-utime \
	   libc-connect libc-fork-exec \
	   kernel_close kernel_dup kernel_dup2

include ../Rules
