
subdir := plash

all:

include ../Makeconfig

routines = filesysobj region comms cap-protocol cap-call-return marshal-pack \
	   cap-utils \
	   libc-comms libc-misc libc-stat \
	   kernel_close kernel_dup kernel_dup2

include ../Rules
